title: Starry Brook HomePage
email: hswswpumn@163com.
description: > # this means to ignore newlines until "baseurl:"
  我唯一锲而不舍，愿意以自己的生命去努力的，只不过是保守我个人的心怀意念，在我有生之日，做一个真诚的人，不放弃对生活的热爱和执着，在有限的时空里，过无限广大的日子。
permalink: ':title/'
baseurl: "/Blog" # the subpath of your site, e.g. /blog
url: "https://hswsp.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Starry Brook # add your name
author-pic: adam-face.jpg
about-author: My name is Shengping. I’m a full-time full stack Engineer and part-time photographer

# Contact links
email: # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: hswsp # Add your Github handle
twitter: '@' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier:  # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]

theme: jekyll-theme-slate
